GettingStarted.Web/Pages/Default/CustomerSave.cshtml.cs
using GettingStarted.DataServices.Default;
using GettingStarted.DataServices.Default.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GettingStarted.Web.Pages.Default
{
    public class CustomerSaveModel : PageModel
    {
        private readonly Service dataService;
        public string? ErrorMessage { set; get; }
        public CustomerSaveInput? Input { set; get; }

        public CustomerSaveModel(Service dataService)
        {
            this.dataService = dataService;
        }

        public void OnGet(int customerId = 0)
        {
            if (customerId == 0)
            {
                Input = new CustomerSaveInput(0, null, null, null, null);
            }
            else
            {
                try
                {
                    var output = dataService.CustomerSelect(new(customerId));

                    if (output.ReturnValue == CustomerSelectOutput.Returns.NotFound)
                    {
                        ErrorMessage = "The customer no longer exists. It more than like was deleted by another administrator.";
                    }
                    else
                    {
                        Input = MapFromResult(output.ResultData!);
                    }

                }
                catch (Exception ex)
                {
                    // Note: This is for illustration only, we would never report this error to an end user in a real world application.
                    ErrorMessage = ex.Message;
                }
            }
        }

        public IActionResult OnPost(CustomerSaveInput input)
        {
            if (input.IsValid())
            {
                try
                {
                    var output = dataService.CustomerSave(input);
                    switch (output.ReturnValue)
                    {
                        case CustomerSaveOutput.Returns.Inserted:
                        case CustomerSaveOutput.Returns.Modified:
                            return Redirect("~/Default/Index");
                        case CustomerSaveOutput.Returns.Duplicate:
                            ErrorMessage = "The email address provided is being used by another customer";
                            break;
                        default:
                            ErrorMessage = "The customer no longer exists. It more than likely was deleted by another administrator.";
                            break;
                    }

                    Input = input;
                }
                catch (Exception ex)
                {
                    // Note: This is for illustration only, we would never report this error to an end user in a real world application.
                    ErrorMessage = ex.Message;

                }
            }
            return Page();
        }

        private CustomerSaveInput MapFromResult(CustomerSelectResult result)
        {
            return new CustomerSaveInput(result.CustomerId, result.CustomerTypeId, result.FirstName, result.LastName, result.Email);
        }

        public int GetPage()
        {
            int result = 1;

            if (Request.HttpContext.Session.GetInt32("page").HasValue)
            {
                result = Request.HttpContext.Session.GetInt32("page")!.Value;
            }

            return result;
        }
    }
}

GettingStarted.Web/Pages/Default/Index.cshtml.cs
using GettingStarted.DataServices.Default;
using GettingStarted.DataServices.Default.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GettingStarted.Web.Pages.Default
{
    public class PagingModel
    {
        public int? PreviousPage { set; get; }
        public int? NextPage { set; get; }
        public int? CurrentPage { set; get; }
        public List<int>? PageItems { set; get; }
    }

    public class IndexModel : PageModel
    {

        private readonly Service dataService;
        public List<CustomerQueryResult>? Customers { set; get; }
        public string? ErrorMessage { set; get; }
        public int? CustomerId { set; get; }
        public PagingModel? Pages { set; get; }

        public IndexModel(Service dataService)
        {
            this.dataService = dataService;
        }

        public void OnGet(int pageNumber = 1)
        {
            Request.HttpContext.Session.SetInt32("page", pageNumber);

            try
            {
                var output = dataService.CustomerQuery(new(10, pageNumber));

                if (output.ReturnValue == CustomerQueryOutput.Returns.Ok)
                {
                    Customers = output.ResultData;
                    Pages = GetPagingModel(pageNumber, output.PageCount!.Value);
                }
            }
            catch (Exception ex)
            {
                // TODO: Log Exception
                // Note we would never want to actually do this in a production environment
                ErrorMessage = ex.Message;
            }
        }

        public void OnGetDeleteCustomer(int customerId)
        {
            try
            {
                dataService.CustomerDelete(new(customerId));
            }
            catch (Exception ex)
            {
                // TODO: Log Exception
                // Note we would never want to actually do this in a production environment
                ErrorMessage = ex.Message;
            }

            OnGet(GetPage());
        }

        private PagingModel? GetPagingModel(int currentPage, int numberOfPages)
        {
            if (numberOfPages > 1)
            {
                int numberOfPagesToDisplay = NumberOfPagesToDisplay(numberOfPages, 9);

                PagingModel result = new() { CurrentPage = currentPage, PageItems = new List<int>() };

                result.PreviousPage = Math.Max(currentPage - 1, 1);
                result.NextPage = Math.Min(currentPage + 1, numberOfPages);

                int firstPageToDisplay = Math.Max(currentPage - 4, 1);
                int lastPageToDisplay = Math.Min(firstPageToDisplay + 8, numberOfPages);
                int rangeToDisplay = lastPageToDisplay - firstPageToDisplay + 1;

                if(rangeToDisplay < numberOfPagesToDisplay)
                {
                    if(lastPageToDisplay == numberOfPages)
                    {
                        firstPageToDisplay = numberOfPages - numberOfPagesToDisplay;
                    }
                    else
                    {
                        lastPageToDisplay = numberOfPages;
                    }
                }
                
                for (int idx = firstPageToDisplay; idx <= lastPageToDisplay; idx++)
                {
                    result.PageItems.Add(idx);
                }

                return result;
            }

            return null;
        }

        private int NumberOfPagesToDisplay(int numberOfPages, int maxNumber)
        {
            int result = Math.Min(numberOfPages, 9);
            return result % 2 == 0 ? result - 1 : result;
        }

        public int GetPage()
        {
            int result = 1;

            if (Request.HttpContext.Session.GetInt32("page").HasValue)
            {
                result = Request.HttpContext.Session.GetInt32("page")!.Value;
            }

            return result;
        }
    }
}

GettingStarted.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace GettingStarted.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

GettingStarted.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GettingStarted.Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

GettingStarted.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GettingStarted.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

GettingStarted.Web/Pages/Default/CustomerSave.cshtml
@page
@model GettingStarted.Web.Pages.Default.CustomerSaveModel
@using GettingStarted.DataServices.Statics

<div class="container w-50">
    <div class="mx-auto shadow p-5 rounded">
        <h2 class="text-center mb-5">Save Customer</h2>
        <div class="mb-4">
            <form method="post">
                <input type="hidden" asp-for="Input!.CustomerId" />
                @if (!string.IsNullOrEmpty(Model.ErrorMessage))
                {
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <strong>Oops!</strong> @Model.ErrorMessage
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                        </button>
                    </div>
                }
                <div class ="form-group mb-3">
                    <label  asp-for="Input!.CustomerTypeId">Customer Type:</label>
                    <select class="form-control" asp-for="Input!.CustomerTypeId">
                        @if(Model.Input!.CustomerId == 0)
                        {
                            <option selected="true" value="">-- Select Type --</option>
                        }
                        @foreach (var customerType in StaticData.CustomerTypeList)
                        {
                            <option value="@customerType.CustomerTypeId">@customerType.Name</option>
                        }
                    </select>
                    <span asp-validation-for="Input!.CustomerTypeId" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="Input!.FirstName">First Name:</label>
                    <input asp-for="Input!.FirstName" class="form-control">
                    <span asp-validation-for="Input!.FirstName" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="Input!.LastName">Last Name:</label>
                    <input asp-for="Input!.LastName" class="form-control">
                    <span asp-validation-for="Input!.LastName" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="Input!.Email">Email:</label>
                    <input asp-for="Input!.Email" class="form-control">
                    <span asp-validation-for="Input!.Email" class="text-danger"></span>
                </div>
                <div class="d-flex justify-content-between">
                    <a asp-page="/Default/Index" asp-route-pageNumber="@Model.GetPage()" class="btn btn-outline-secondary w-25">Cancel</a>
                    <button type="submit" class="btn btn-primary w-25">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

GettingStarted.Web/Pages/Default/Index.cshtml
@page
@model GettingStarted.Web.Pages.Default.IndexModel
<h4 class="py-1">Customers</h4>
<table class="table  table-sm table-bordered ">
    <thead>
        <tr>
            <th></th>
            <th>Customer ID</th>
            <th>First Name</th>
            <th>Last Name </th>
            <th>Email</th>
            <th class="text-center">
                <a asp-page="/Default/CustomerSave" title="Add a new custmer" class="text-center">
                    <i class="fa fa-plus"></i>
                </a>
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Customers is null)
        {
            <tr>
                <td colspan="6" class="text-center">
                    <p class="px-3 py-3">
                        You currently have no customers.
                        Click on the <i class="fa fa-plus text-primary"></i> icon to add customers.
                    </p>
                </td>
            </tr>
        }
        else
        {
            foreach (var customer in Model.Customers)
            {
                <tr>

                    @if (customer.CustomerTypeId == 1)
                    {
                        <td align="center" width="48px" title="Residential Customer">
                            <i class="fa fa-house"></i>
                        </td>
                    }
                    @if (customer.CustomerTypeId == 2)
                    {
                        <td align="center" width="48px" title="Commercial Customer">
                            <i class="fa fa-building"></i>
                        </td>
                    }

                    <td>@customer.CustomerId</td>
                    <td>@customer.FirstName</td>
                    <td>@customer.LastName</td>
                    <td>
                        <a asp-page="/Default/CustomerSave" asp-route-customerId="@customer.CustomerId">
                            @customer.Email
                        </a>
                    </td>
                    <td align="center" width="48px">
                        <a asp-page-handler="DeleteCustomer" asp-route-customerId="@customer.CustomerId" onclick="return confirm('Permanently delete @customer.FirstName @customer.LastName?')">
                            <i class="fa fa-trash text-danger"></i>
                        </a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
@if (Model.Pages is not null)
{
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end">
            <li class="page-item @(Model.Pages.PreviousPage is null ? "disabled" : String.Empty)">
                <a class="page-link" asp-page="/Default/Index" asp-route-pageNumber="@Model.Pages.PreviousPage">Previous</a>
            </li>
            @foreach (int pageItem in Model.Pages.PageItems!)
            {
                <li class="page-item text-center @(Model.Pages.CurrentPage == pageItem ? "disabled" : String.Empty)" style="width:3rem;">
                    <a class="page-link" asp-page="/Default/Index" asp-route-pageNumber="@pageItem">@pageItem</a>
                </li>
            }
            <li class="page-item @(Model.Pages.NextPage is null ? "disabled" : String.Empty)">
                <a class="page-link" asp-page="/Default/Index" asp-route-pageNumber="@Model.Pages.NextPage">Next</a>
            </li>
        </ul>
    </nav>
}

GettingStarted.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<div class="w-75 mx-auto">
    <h3 class="py-1">Welcome to the SQL+ Getting Started Walkthrough</h3>
    <h4 class="py-1">Before you start</h4>
    <p>
        Make sure to follow the instructions in the "ReadMe.md" file in the root folder.
    </p>
    <p>
        After completeing these steps all pages should function correctly.
    </p>
    <h4 class="py-1">
        Exploring this project
    </h4>
    <p>
        This application illustrates.
        <ol>
            <li><b>CustomerQuery</b> - Retrieves a paged set of customers</li>
            <li><b>CustomerSelect</b> - Retrieves a customer by customer id</li>
            <li><b>CustomerSave</b> - Inserts or updates a customer</li>
            <li><b>CustomerDelete</b> - Deletes an existing customer by customer id.</li>
        </ol>
    </p>
    <h4 class="py-1">
        Running and Testing
    </h4>
    <p class="py-1">
        You can put break points on the "OnGet", "OnDelete"" and "OnPost" methods in the Index.cs and CustomerSave.cs pages to see the code in action.
    </p>
    <p class="py-1">
        Try adding new customers with both valid and invalid data to see the behaviour of the various services and application of the tags.
    </p>
    <p>
        Check out more at the <a href="https://www.sqlplus.net" target="_blank">SQL+ Website</a>
    </p>
</div>

GettingStarted.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GettingStarted.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GettingStarted.Web.styles.css" asp-append-version="true" />
    <script src="~/fontawesome/js/all.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Default/Index">Customers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GettingStarted.Web - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    

</body>
</html>